version: '3'
services:
    weather:
        container_name: weather
        image: tran/weather
        restart: always
        build: .
        ports:
            - '3001:3000'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - /Users/cuongqtran/personal/database:/data/db
        ports:
            - '27018:27017'
